### ISSUE TITLE
cluster discovery

### ISSUE THREAD

**Issue by ghost** [shijuvar/go-distributed-sys#1]
am a bit confused about how each server finds the others int eh cluster.

DO you run Consul ?

**Comment by shijuvar** [comment]
@gedw99  The purpose of the example is to discuss about event-driven architectures to solve the practical challenges of microservices because of the data is scattered into multiple databases owned by individual microservices. It does not focus on load balancing, service registry and service discovery, which I consider as infrastructure things that is not the complex part. If you run your microservices in production, I highly recommend for running it with a service mesh platform like Istio (https://istio.io), which provides service discovery, load balancing, failure recovery, metrics, and monitoring.

**Comment by ghost** [comment]
thanks @shijuvar for the istio recommendation.

I will look into it
